version: '2'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  thehive:
    image: 'thehiveproject/thehive:3.5.1-1'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9000:9000'
    volumes:
      - './etc/thehive/application.conf:/etc/thehive/application.conf'
      - './opt/data:/opt/data'
    command: '--no-config --no-config-secret'
