version: '3.8'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - '0.0.0.0:9200:9200'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - cluster.name=hive
      - script.allowed_types= inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
      - gateway.recover_after_nodes=1
      - xpack.security.enabled=false
      - bootstrap.memory_lock=true
      - 'ES_JAVA_OPTS=-Xms256m -Xmx256m'
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - ./elasticsearch_data:/usr/share/elasticsearch/data
      - ./elasticsearch_logs:/usr/share/elasticsearch/logs

  cortex:
    image: 'thehiveproject/cortex:3.1.1-1'
    container_name: cortex
    restart: unless-stopped    
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${job_directory}:${job_directory}'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'

  thehive:
    image: 'thehiveproject/thehive:3.5.1-1'
    container_name: thehive
    restart: unless-stopped
    depends_on:
      - elasticsearch
      - cortex
    ports:
      - '0.0.0.0:9000:9000'
    command: '--cortex-port 9001'
