version: '2'
services:
  elasticsearch:
    image: 'elasticsearch:7.11.1'
    environment:
      - http.host=0.0.0.0
      - discovery.type=single-node
      - script.allowed_types=inline
      - thread_pool.search.queue_size=100000
      - thread_pool.write.queue_size=10000
  cortex:
    image: 'thehiveproject/cortex:3.1.1-1'
    environment:
      - 'job_directory=${job_directory}'
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
      - '${job_directory}:${job_directory}'
    depends_on:
      - elasticsearch
    ports:
      - '0.0.0.0:9001:9001'
